apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: v4-helm-inter-gw-ms-v1-vamos-nomecumprido-vamoslog
  namespace: argocd
spec: 
  destination: 
    namespace: helm-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: helm-guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
    helm:
     releaseName: v4-helm-inter-gw-ms-v1-vamos-nomecumprido-vamoslog
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
